# ------------------------------------------------------------------------------
# Istio Control Plane
#
# **WARNING**: This is currently using a custom build which supports GIE.
#
# This deploys the Istio Control Plane to enable the creation of Gateways.
# It is expected that the CRDs are deployed separately, before deploying
# this.
#
# ------------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

resources:
- namespaces.yaml
- configmaps.yaml
- policies.yaml
- service-accounts.yaml
- rbac.yaml
- services.yaml
- webhooks.yaml
- deployments.yaml
- hpa.yaml
- telemetry.yaml
