apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${NAMESPACE}

resources:
  - deployments/vllm-deployment.yaml
  - deployments/redis-deployment.yaml
  - service/redis-service.yaml
  - deployments/secret.yaml

images:
  - name: vllm/vllm-openai
    newName: ${VLLM_IMAGE}
    newTag: ${VLLM_TAG}
  - name: redis
    newName: ${REDIS_IMAGE}
    newTag: ${REDIS_TAG}
