apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${NAMESPACE}

resources:
  - deployments/vllm-deployment.yaml
  - deployments/redis-deployment.yaml
  - service/redis-service.yaml
  - pvc/volume.yaml
  - deployments/secret.yaml

images:
  - name: vllm/vllm-openai
    newName: ${VLLM_IMAGE}
    newTag: ${VLLM_TAG}
  - name: redis
    newName: ${REDIS_IMAGE}
    newTag: ${REDIS_TAG}

configMapGenerator:
  - name: model-config
    literals:
      - MODEL_NAME=${MODEL_NAME}
      - MODEL_LABEL=${MODEL_LABEL}
      - POOL_LABEL=${POOL_LABEL}
      - REDIS_ENABLED=${REDIS_ENABLED}

generatorOptions:
  disableNameSuffixHash: true