apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../components/vllm-p2p/

images:
- name: quay.io/llm-d/llm-d-dev:0.0.2
  newName: ${VLLM_IMAGE}
  newTag: ${VLLM_TAG}

patches:
  - path: patch-deployments.yaml
