run:
  timeout: 5m
  allow-parallel-runners: true
    
# Settings related to issues
issues:
  # Report issues on new code only (since we're brining in from upstream)
  new: true
  # Which dirs to exclude: issues from them won't be reported
  exclude-dirs:
    - bin
    
linters:
  disable-all: true
  enable:
    - copyloopvar
    - dupword
    - durationcheck
    - fatcontext
    - ginkgolinter
    - gocritic
    # - govet        # do not enable - this causes some metalinter issue
    - loggercheck
    - misspell
    - perfsprint
    - revive
    - unconvert
    - makezero
    - errcheck
    - goconst
    - ineffassign
    - nakedret
    - prealloc
    - unparam
    - unused

linters-settings:
  revive:
    rules:
      - name: comment-spacings