apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${VLLM_DEPLOYMENT_NAME}
  labels:
    app.kubernetes.io/name: vllm
    app.kubernetes.io/model: ${MODEL_LABEL}
    app.kubernetes.io/component: vllm
spec:
  replicas: ${VLLM_REPLICA_COUNT}
  selector:
    matchLabels:
      app.kubernetes.io/name: vllm
      app.kubernetes.io/component: vllm
      app.kubernetes.io/model: ${MODEL_LABEL}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vllm
        app.kubernetes.io/component: vllm
        app.kubernetes.io/model: ${MODEL_LABEL}
    spec:
      containers:
        - name: vllm
          image: ${VLLM_IMAGE}:${VLLM_TAG}
          imagePullPolicy: Always
          command:
            - /bin/sh
            - "-c"
          args:
            - |
              export LMCACHE_DISTRIBUTED_URL=${POD_IP}:80 &&
              vllm serve ${MODEL_NAME}
              --host 0.0.0.0
              --port 8000
              --enable-chunked-prefill false
              --max-model-len ${MAX_MODEL_LEN}
              --kv-transfer-config
              '{"kv_connector":"LMCacheConnector","kv_role":"kv_both"}'
          ports:
            - name: http
              containerPort: 8000
            - name: lmcache-dist
              containerPort: 80
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ${HF_SECRET_NAME}
                  key: ${HF_SECRET_KEY}
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: model-storage
              mountPath: ${VOLUME_MOUNT_PATH}
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName: ${PVC_NAME}
