# ------------------------------------------------------------------------------
# KGateway Control Plane
#
# A Gateway API implementation with support for the GIE.
# ------------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces.yaml

helmCharts:
  - name: kgateway
    repo: oci://cr.kgateway.dev/kgateway-dev/charts
    version: v2.0.0
    releaseName: kgateway
    namespace: kgateway-system
    valuesInline:
      inferenceExtension:
        enabled: true
