# ------------------------------------------------------------------------------
# Custom Resource Definitions (CRDs) for KGateway
#
# **Warning**: CRDs are cluster-level, so in a shared development environment
# this needs to be done in a controlled and communicated manner.
# ------------------------------------------------------------------------------
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespaces.yaml

helmCharts:
- name: kgateway-crds
  repo: oci://cr.kgateway.dev/kgateway-dev/charts
  version: v2.0.0
  releaseName: kgateway-crds
  namespace: kgateway-system
