apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Set the namespace for all resources using a placeholder.
namespace: ${NAMESPACE}

# Use a prefix for all object names. You can substitute the PROJECT_NAME variable.
namePrefix: ${PROJECT_NAME}-

# List all the resources (manifests) you want to deploy.

# Include patches to update existing resources, if any
