apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../components/vllm/

images:
- name: quay.io/vllm-d/vllm-d-dev:0.0.2
  newName: ${VLLM_IMAGE}
  newTag: ${VLLM_TAG}

