apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../components/vllm-sim/

images:
- name: quay.io/vllm-d/vllm-sim
  newTag: ${VLLM_SIM_TAG}

patches:
  - path: patch-deployments.yaml

