apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoint-picker
spec:
  template:
    spec:
      containers:
      - name: epp
        args:
        - -poolName
        - ${POOL_NAME}
        - -poolNamespace
        - "default"
        - -v
        - "4"
        - --zap-encoder
        - "json"
        - -grpcPort
        - "9002"
        - -grpcHealthPort
        - "9003"
