kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: endpoint-picker
rules:
- apiGroups:
  - "inference.networking.x-k8s.io"
  resources:
  - "inferencepools"
  - "inferencemodels"
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - ""
  resources:
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - "discovery.k8s.io"
  resources:
  - "endpointslices"
  verbs:
  - "get"
  - "watch"
  - "list"
- apiGroups:
  - "authentication.k8s.io"
  resources:
  - "tokenreviews"
  verbs:
  - "create"
- apiGroups:
  - "authorization.k8s.io"
  resources:
  - "subjectaccessreviews"
  verbs:
  - "create"
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: endpoint-picker-binding
subjects:
- kind: ServiceAccount
  name: endpoint-picker
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: endpoint-picker
