apiVersion: v1
kind: Service
metadata:
  name: endpoint-picker
spec:
  selector:
    app: endpoint-picker
  ports:
  - protocol: TCP
    port: 9002
    targetPort: 9002
    appProtocol: http2
  type: ClusterIP
