apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${PVC_NAME}
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: vllm
    app.kubernetes.io/component: storage
    app.kubernetes.io/model: ${MODEL_LABEL}
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ${PVC_ACCESS_MODE}
  resources:
    requests:
      storage: ${PVC_SIZE}
  storageClassName: ${PVC_STORAGE_CLASS}
