apiVersion: v1
kind: Service
metadata:
  name: inference-gateway
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: inference-gateway
    app.kubernetes.io/name: inference-gateway
    gateway.networking.k8s.io/gateway-name: inference-gateway
  ports:
    - name: default
      nodePort: 30080
      port: 80
      protocol: TCP
      targetPort: 8080
